# Generated by Django 5.1.15 on 2026-09-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="education",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="github_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="portfolio_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="work_experience",
            field=models.TextField(blank=True),
        ),
    ]
