# Generated by Django 5.2.8 on 2026-09-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_candidate_profile_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='show_education',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='show_github',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='show_headline',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='show_linkedin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='show_location',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='show_portfolio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='show_skills',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='show_summary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='show_work_experience',
            field=models.BooleanField(default=True),
        ),
    ]
