# Generated by Django 5.1.15 on 2026-09-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_posting_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('REVIEW', 'Review'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('CLOSED', 'Closed')], default='APPLIED', max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
