# Generated by Django 5.1.15 on 2026-09-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobapplication_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='moderation_note',
            field=models.TextField(blank=True),
        ),
    ]
